import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { FloatingDockDemo } from "@/components/layout/FloatingNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarDemo />
        {children}
        <FloatingDockDemo />
        <Footer />
      </body>
    </html>
  );
}
